# This file will hold any hard configurations MailCannon may need. Customizations included.

# When creating a MailCannon::Envelope the default behavior is to auto-post the Job to send it.
auto_post: true

# This is will schedule a delay for the Job execution, useful if you want to be able to Cancel the Job.
waiting_time: 0

# Pretty self explanatory. This is intended to be used by your event consuming service.
add_envelope_id_to_unique_args: true